# Generated by Django 3.1.1 on 2022-02-04 07:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropKing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('player1_name', models.CharField(max_length=100)),
                ('player2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('player1_email', models.EmailField(max_length=255)),
                ('player2_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('player1_score', models.IntegerField(blank=True, null=True)),
                ('player2_score', models.IntegerField(blank=True, null=True)),
                ('game_name', models.CharField(max_length=255)),
                ('game_date', models.DateTimeField()),
                ('game_time', models.DateTimeField()),
                ('player1_picks', models.CharField(blank=True, max_length=100, null=True)),
                ('player2_picks', models.CharField(blank=True, max_length=100, null=True)),
                ('challenge_accepted', models.BooleanField(default=False)),
                ('game_completed', models.BooleanField(default=False)),
                ('game_setttled', models.BooleanField(default=False)),
            ],
        ),
       # migrations.AddField(
        #    model_name='profile',
         #   name='model_limit',
          #  field=models.IntegerField(default=10),
        #),
       # migrations.AddField(
        #    model_name='profile',
         #   name='models_built_today',
          #  field=models.IntegerField(default=0),
        #),
        migrations.AlterField(
            model_name='betacode',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
