# Generated by Django 3.1.1 on 2022-02-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220204_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='model_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='models_built_today',
            field=models.IntegerField(default=0),
        ),
    ]
