# Generated by Django 3.1.1 on 2022-02-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220208_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propking',
            name='game_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propking',
            name='game_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
