# Generated by Django 3.1.1 on 2022-02-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_propking_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='propking',
            name='props_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
