# Generated by Django 3.1.1 on 2022-02-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_propking_props_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propking',
            name='game_time',
        ),
        migrations.RemoveField(
            model_name='propking',
            name='player1_picks',
        ),
        migrations.RemoveField(
            model_name='propking',
            name='player1_prop_type',
        ),
        migrations.RemoveField(
            model_name='propking',
            name='player1_score',
        ),
        migrations.RemoveField(
            model_name='propking',
            name='player2_picks',
        ),
        migrations.RemoveField(
            model_name='propking',
            name='player2_prop_type',
        ),
        migrations.RemoveField(
            model_name='propking',
            name='player2_score',
        ),
        migrations.RemoveField(
            model_name='propking',
            name='props_player1_data',
        ),
        migrations.RemoveField(
            model_name='propking',
            name='props_player2_data',
        ),
    ]
