# Generated by Django 3.1.1 on 2022-03-04 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220228_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prop_king_game_played',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_propking', to='users.propmaster'),
        ),
    ]
