# Generated by Django 3.1.1 on 2022-04-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20220407_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='propmaster',
            name='sport',
            field=models.CharField(blank=True, default='NBA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prop_master_game_played',
            field=models.ManyToManyField(blank=True, related_name='profile_propmaster_m2m', to='users.PropMaster'),
        ),
    ]
