# Generated by Django 3.1.1 on 2022-08-18 06:04

from django.db import migrations, models
import phonenumber_field.modelfields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20220407_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=160, null=True, verbose_name='profile_bio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='discord_Username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='discord_username'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='eg: +12223334444x55', max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True, validators=[users.models.validate_twitter_url], verbose_name='twitter_url'),
        ),
    ]
