# Generated by Django 3.1.1 on 2022-09-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20220906_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_comments_posts',
            field=models.BooleanField(default=False, help_text='received email when someone comments on the post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Profile Bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prop_master_game_played',
            field=models.ManyToManyField(blank=True, related_name='profile_propmaster_m2m', to='users.PropMaster'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Twitter Handle'),
        ),
    ]
