# Generated by Django 3.1.1 on 2021-06-23 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDatafilesZip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zip_name', models.CharField(blank=True, max_length=200, unique=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Activate Dataset',
                'verbose_name_plural': 'Activate Dataset',
            },
        ),
        migrations.CreateModel(
            name='BetaCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('user_connected', models.CharField(blank=True, max_length=200)),
                ('flag', models.IntegerField(blank=True, choices=[(1, 'UserUsed'), (2, 'AdminBetaInvite'), (3, 'UserBetaSendEmail')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='S3ZipUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(blank=True, choices=[('a', 'a')], max_length=20, null=True)),
                ('file', s3direct.fields.S3DirectField()),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Upload Dataset(Zipfile)',
                'verbose_name_plural': 'Upload Dataset(Zipfile)',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSportsChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports', models.ManyToManyField(to='blog.BlogSports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Sport Choices',
                'verbose_name_plural': 'User Sport Choices',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='defaultProfile.png?v=1', null=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('follow_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BetacodeInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sended_date', models.DateTimeField(auto_now_add=True)),
                ('flag_betacode', models.IntegerField(blank=True, choices=[(1, 'UserUsed'), (2, 'AdminBetaInvite'), (3, 'UserBetaSendEmail')], null=True)),
                ('user_sended_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('user_mail_send_date', models.DateTimeField(blank=True, null=True)),
                ('betacode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betacode', to='users.betacode')),
                ('user_sended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sended', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
