# Generated by Django 3.1.1 on 2022-02-08 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_propking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='propking',
            name='prop_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propking_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
