# Generated by Django 3.1.1 on 2022-02-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220208_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propking',
            old_name='prop_type',
            new_name='player1_prop_type',
        ),
        migrations.AddField(
            model_name='propking',
            name='player2_prop_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propking',
            name='player1_picks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propking',
            name='player2_picks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
