# Generated by Django 3.1.1 on 2022-02-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220208_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='propking',
            name='props_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
