# Generated by Django 3.1.1 on 2022-02-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_propking_props_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propking',
            name='props_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
