# Generated by Django 3.1.1 on 2022-02-10 06:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220210_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='propking',
            name='props_player1',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
