# Generated by Django 3.1.1 on 2022-02-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_propking_props_player1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propking',
            name='props_data',
        ),
        migrations.RemoveField(
            model_name='propking',
            name='props_player1',
        ),
        migrations.AddField(
            model_name='propking',
            name='props_player1_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propking',
            name='props_player2_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
