# Generated by Django 3.1.1 on 2022-02-24 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220210_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='propking',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
