# Generated by Django 3.1.1 on 2022-02-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220224_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='propking',
            name='player1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propking',
            name='player2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propking',
            name='winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
