# Generated by Django 3.1.1 on 2022-03-30 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_usernotification_prop_king_game'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0017_auto_20220304_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropKing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('player1_name', models.CharField(max_length=100)),
                ('player2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('player1_email', models.EmailField(max_length=255)),
                ('player2_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('game_name', models.CharField(max_length=255)),
                ('game_date', models.DateTimeField(blank=True, null=True)),
                ('props_data', models.JSONField(blank=True, null=True)),
                ('challenge_accepted', models.BooleanField(default=False)),
                ('game_completed', models.BooleanField(default=False)),
                ('game_setttled', models.BooleanField(default=False)),
                ('player1_score', models.IntegerField(blank=True, null=True)),
                ('player2_score', models.IntegerField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propmaster_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prop_king_game_played',
        ),
        migrations.DeleteModel(
            name='PropKing',
        ),
        migrations.AddField(
            model_name='profile',
            name='prop_master_game_played',
            field=models.ManyToManyField(blank=True, related_name='profile_propmaster_m2m', to='users.PropKing'),
        ),
    ]
