# Generated by Django 3.1.1 on 2021-07-15 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pineproxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictMLBUserFormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predict_type', models.CharField(max_length=255)),
                ('predict_year', models.CharField(max_length=255)),
                ('predict_train', models.CharField(max_length=255)),
                ('predict_stats', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict_mlb_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
