# Generated by Django 3.1.1 on 2021-07-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pineproxy', '0002_predictmlbuserformdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictmlbuserformdata',
            name='predict_stats',
            field=models.TextField(),
        ),
    ]
