# Generated by Django 3.1.1 on 2021-08-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pineproxy', '0003_auto_20210721_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictmlbuserformdata',
            name='model_name',
            field=models.CharField(default='no name', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictmlbuserformdata',
            name='model_score',
            field=models.FloatField(default=-1),
        ),
    ]
