# Generated by Django 3.1.1 on 2021-08-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pineproxy', '0004_auto_20210809_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictmlbuserformdata',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predictmlbuserformdata',
            name='model_type',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
