# Generated by Django 3.1.1 on 2021-08-10 11:21

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pineproxy', '0005_auto_20210810_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineSpreadsheetUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', s3direct.fields.S3DirectField()),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Line Spreadsheet upload',
                'verbose_name_plural': 'Line Spreadsheet upload',
            },
        ),
    ]
