# Generated by Django 3.1.1 on 2021-08-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pineproxy', '0006_linespreadsheetupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveLineDatafilesCsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_csv_name', models.CharField(blank=True, max_length=200, unique=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Activate Line Dataset',
                'verbose_name_plural': 'Activate Line Dataset',
            },
        ),
        migrations.AddField(
            model_name='sports_name',
            name='active_line_csv_dataset',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
