# Generated by Django 3.1.1 on 2021-08-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pineproxy', '0007_auto_20210810_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictmlbuserformdata',
            name='last_game',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
