# Generated by Django 3.1.1 on 2021-08-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pineproxy', '0008_predictmlbuserformdata_last_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictmlbuserformdata',
            name='last_game',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
