# Generated by Django 3.1.1 on 2021-08-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pineproxy', '0009_auto_20210817_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictmlbuserformdata',
            name='model_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='predictmlbuserformdata',
            name='models_built_today',
            field=models.IntegerField(default=0),
        ),
    ]
