# Generated by Django 3.1.1 on 2021-10-12 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pineproxy', '0014_predictnbauserformdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictNHLUserFormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=250)),
                ('model_score', models.FloatField(default=-1)),
                ('active', models.BooleanField(default=False)),
                ('model_type', models.CharField(default='None', max_length=255)),
                ('predict_type', models.CharField(max_length=255)),
                ('predict_year', models.CharField(max_length=255)),
                ('predict_train', models.CharField(max_length=255)),
                ('predict_stats', models.TextField()),
                ('last_game', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict_nhl_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
