# Generated by Django 3.1.1 on 2022-02-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pineproxy', '0015_predictnhluserformdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataframe',
            name='file',
            field=models.FileField(upload_to='props_test/'),
        ),
    ]
