# Generated by Django 4.2.13 on 2024-10-28 22:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('league', models.CharField(db_index=True, max_length=20)),
                ('published', models.BigIntegerField(db_index=True)),
                ('author', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500, unique=True)),
                ('domain', models.CharField(max_length=50, null=True)),
                ('title_from_site', models.TextField(null=True)),
                ('summary', models.TextField()),
                ('ai_summary', models.TextField()),
                ('embeddings_string', models.TextField()),
                ('embeddings', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('author_from_site', models.TextField(null=True)),
                ('bettor_rating', models.IntegerField(db_index=True, null=True)),
                ('cover_image', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportsTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(db_index=True)),
                ('username', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=500, unique=True)),
                ('text', models.TextField()),
                ('embeddings_string', models.TextField()),
                ('embeddings', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('bettor_rating', models.IntegerField(db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(db_index=True, max_length=100)),
                ('sports_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.sportsnews')),
            ],
            options={
                'unique_together': {('sports_news', 'team')},
            },
        ),
        migrations.CreateModel(
            name='PlayerNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(db_index=True, max_length=100)),
                ('sports_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.sportsnews')),
            ],
            options={
                'unique_together': {('sports_news', 'player')},
            },
        ),
    ]
