from django import forms

class MLBForm(forms.Form):

    STATS_INCLUDE_OPTIONS = (
        ("Game - Season", "Season"),
        ("Game - Date", "Date"),
        ("Game - Venue", "Venue"),
        ("Game - Temperature", "Temperature"),
        ("Game - Wind Speed", "Wind Speed"),
        ("Game - Park Factor", "Park Factor"),
        ("Game - Park Factor - wOBACon", "Park Factor - wOBACon"),
        ("Game - Park Factor - xwOBACon", "Park Factor - xwOBACon"),
        ("Game - Park Factor - BACON", "Park Factor - BACON"),
        ("Game - Park Factor - xBACON", "Park Factor - xBACON"),
        ("Game - Park Factor - Hard Hit", "Park Factor - Hard Hit"),
        ("Game - Park Factor - Runs", "Park Factor - Runs"),
        ("Game - Park Factor - On Base Percentage", "Park Factor - On Base Percentage"),
        ("Game - Park Factor - Hits", "Park Factor - Hits"),
        ("Game - Park Factor - First Base", "Park Factor - First Base"),
        ("Game - Park Factor - Second Base", "Park Factor - Second Base"),
        ("Game - Park Factor - Third Base", "Park Factor - Third Base"),
        ("Game - Park Factor - Home Runs", "Park Factor - Home Runs"),
        ("Game - Park Factor - Bases on Balls", "Park Factor - Bases on Balls"),
        ("Game - Park Factor - Strikeouts", "Park Factor - Strikeouts"),
        ("Game - Park Factor - Plate Appearances", "Park Factor - Plate Appearances"),
        ("Game - Implied Odds", "Implied Odds"),
        ("Game - Point Spread", "Point Spread"),
        ("Game - Point Spread Implied Odds", "Point Spread Implied Odds"),
        ("Game - Over-Under", "Over-Under"),
        ("Team and Opponent - Starting Pitcher", "Starting Pitcher"),
        ("Historic - Game - Implied Odds", "Implied Odds in Past Games"),
        ("Historic - Game - Final Score Spread", "Final Score Spread in Past Games"),
        ("Historic - Game - Point Spread", "Point Spread in Past Games"),
        ("Historic - Game - Point Spread Implied Odds", "Point Spread Implied Odds in Past Games"),
        ("Historic - Game - Spread Difference", "Spread Difference in Past Games"),
        ("Historic - Game - Total Score", "Total Score in Past Games"),
        ("Historic - Game - Total Score - First Five Innings", "Total Score - First Five Innings in Past Games"),
        ("Historic - Game - Over-Under", "Over-Under"),
        ("Historic - Game - Over-Under Difference", "Over-Under Difference in Past Games"),
        ("Historic - Game - Temperature", "Temperature in Past Games"),
        ("Historic - Game - Wind Speed", "Wind Speed in Past Games"),
        ("Historic - Game - Park Factor", "Park Factor - Past Games"),
        ("Historic - Game - Park Factor - wOBACon", "Park Factor - wOBACon - Past Games"),
        ("Historic - Game - Park Factor - xwOBACon", "Park Factor - xwOBACon - Past Games"),
        ("Historic - Game - Park Factor - BACON", "Park Factor - BACON - Past Games"),
        ("Historic - Game - Park Factor - xBACON", "Park Factor - xBACON - Past Games"),
        ("Historic - Game - Park Factor - Hard Hit", "Park Factor - Hard Hit - Past Games"),
        ("Historic - Game - Park Factor - Runs", "Park Factor - Runs - Past Games"),
        ("Historic - Game - Park Factor - On Base Percentage", "Park Factor - On Base Percentage - Past Games"),
        ("Historic - Game - Park Factor - Hits", "Park Factor - Hits - Past Games"),
        ("Historic - Game - Park Factor - First Base", "Park Factor - First Base - Past Games"),
        ("Historic - Game - Park Factor - Second Base", "Park Factor - Second Base - Past Games"),
        ("Historic - Game - Park Factor - Third Base", "Park Factor - Third Base - Past Games"),
        ("Historic - Game - Park Factor - Home Runs", "Park Factor - Home Runs - Past Games"),
        ("Historic - Game - Park Factor - Bases on Balls", "Park Factor - Bases on Balls - Past Games"),
        ("Historic - Game - Park Factor - Strikeouts", "Park Factor - Strikeouts - Past Games"),
        ("Historic - Game - Park Factor - Plate Appearances", "Park Factor - Plate Appearances - Past Games"),
        ("Historic - Team and Opponent - Season Win Percentage", "Season Win Percentage"),
        ("Historic - Team and Opponent - Runs", "Runs"),
        ("Historic - Team and Opponent - Hits", "Hits"),
        ("Historic - Team and Opponent - Errors", "Errors"),
        ("Historic - Team and Opponent - 1st Inning", "1st Inning Runs"),
        ("Historic - Team and Opponent - 2nd Inning", "2nd Inning Runs"),
        ("Historic - Team and Opponent - 3rd Inning", "3rd Inning Runs"),
        ("Historic - Team and Opponent - 4th Inning", "4th Inning Runs"),
        ("Historic - Team and Opponent - 5th Inning", "5th Inning Runs"),
        ("Historic - Team and Opponent - 6th Inning", "6th Inning Runs"),
        ("Historic - Team and Opponent - 7th Inning", "7th Inning Runs"),
        ("Historic - Team and Opponent - 8th Inning", "8th Inning Runs"),
        ("Historic - Team and Opponent - 9th Inning", "9th Inning Runs"),
        ("Historic - Team and Opponent - First Five Innings", "First Five Innings"),
        ("Historic - Team and Opponent - Batting - At Bats", "Batting - At Bats"),
        ("Historic - Team and Opponent - Batting - Runs", "Batting - Runs"),
        ("Historic - Team and Opponent - Batting - Hits", "Batting - Hits"),
        ("Historic - Team and Opponent - Batting - RBIs", "Batting - RBIs"),
        ("Historic - Team and Opponent - Batting - Bases on Balls", "Batting - Bases on Balls"),
        ("Historic - Team and Opponent - Batting - 1st Base", "Batting - 1st Base"),
        ("Historic - Team and Opponent - Batting - 2nd Base", "Batting - 2nd Base"),
        ("Historic - Team and Opponent - Batting - 3rd Base", "Batting - 3rd Base"),
        ("Historic - Team and Opponent - Batting - Home Run", "Batting - Home Run"),
        ("Historic - Team and Opponent - Batting - Total Bases", "Batting - Total Bases"),
        ("Historic - Team and Opponent - Batting - Stolen Bases", "Batting - Stolen Bases"),
        ("Historic - Team and Opponent - Batting - Hit By Pitch", "Batting - Hit By Pitch"),
        ("Historic - Team and Opponent - Batting - Strikeouts", "Batting - Strikeouts"),
        ("Historic - Team and Opponent - Batting - Plate Appearances", "Batting - Plate Appearances"),
        ("Historic - Team and Opponent - Batting - Pitches", "Batting - Pitches"),
        ("Historic - Team and Opponent - Batting - Strikes", "Batting - Strikes"),
        ("Historic - Team and Opponent - Batting - Putouts", "Batting - Putouts"),
        ("Historic - Team and Opponent - Batting - Assists", "Batting - Assists"),
        ("Historic - Team and Opponent - Batting - Batting Average", "Batting - Batting Average"),
        ("Historic - Team and Opponent - Batting - Slugging Percentage", "Batting - Slugging Percentage"),
        ("Historic - Team and Opponent - Batting - On Base Percentage", "Batting - On Base Percentage"),
        ("Historic - Team and Opponent - Batting - On Base and Slugging Percentage", "Batting - On Base and Slugging Percentage"),
        ("Historic - Team and Opponent - Batting - Isolated Power", "Batting - Isolated Power"),
        ("Historic - Team and Opponent - Batting - Balls in Play", "Batting - Balls in Play"),
        ("Historic - Team and Opponent - Batting - Batting Average on Balls in Play", "Batting - Batting Average on Balls in Play"),
        ("Historic - Team and Opponent - Batting - Walk Rate", "Batting - Walk Rate"),
        ("Historic - Team and Opponent - Batting - Strikeout Rate", "Batting - Strikeout Rate"),
        ("Historic - Team and Opponent - Batting - Walk to Strikeout Ratio", "Batting - Walk to Strikeout Ratio"),
        ("Historic - Team and Opponent - Pitching - Innings Pitched", "Pitching - Innings Pitched"),
        ("Historic - Team and Opponent - Pitching - Hits", "Pitching - Hits"),
        ("Historic - Team and Opponent - Pitching - Runs", "Pitching - Runs"),
        ("Historic - Team and Opponent - Pitching - Earned Runs Allowed", "Pitching - Earned Runs Allowed"),
        ("Historic - Team and Opponent - Pitching - Earned Runs Allowed Average", "Pitching - Earned Runs Allowed Average"),
        ("Historic - Team and Opponent - Pitching - Pitches", "Pitching - Pitches"),
        ("Historic - Team and Opponent - Pitching - Strikes", "Pitching - Strikes"),
        ("Historic - Team and Opponent - Pitching - Bases on Balls", "Pitching - Bases on Balls"),
        ("Historic - Team and Opponent - Pitching - Strikeouts", "Pitching - Strikeouts"),
        ("Historic - Team and Opponent - Pitching - Saves", "Pitching - Saves"),
        ("Historic - Team and Opponent - Pitching - Home Run", "Pitching - Home Run"),
        ("Historic - Team and Opponent - Pitching - Quality Start", "Pitching - Quality Start"),
        ("Historic - Team and Opponent - Pitching - Hit Batsman", "Pitching - Hit Batsman"),
        ("Historic - Team and Opponent - Pitching - Complete Game", "Pitching - Complete Game"),
        ("Historic - Team and Opponent - Pitching - Complete Game Shutout", "Pitching - Complete Game Shutout"),
        ("Historic - Team and Opponent - Pitching - No Hitter", "Pitching - No Hitter"),
        ("Historic - Team and Opponent - Pitching - Batters Faced", "Pitching - Batters Faced"),
        ("Historic - Team and Opponent - Pitching - Ground-Balls", "Pitching - Ground-Balls"),
        ("Historic - Team and Opponent - Pitching - Fly Balls & Popups", "Pitching - Fly Balls & Popups"),
        ("Historic - Team and Opponent - Pitching - Line Drives", "Pitching - Line Drives"),
    )
    PREDICT_TYPE_OPTIONS = (
        ("Winner", "Winner"),
        ("Winner Against The Spread", "Winner Against The Spread"),
        ("Over-Under Result", "Over-Under"),
    )

    model_name = forms.CharField()
    model_score = forms.FloatField()
    active = forms.BooleanField()
    model_type = forms.CharField()
    predict_type = forms.ChoiceField(choices=PREDICT_TYPE_OPTIONS,widget=forms.Select(attrs={'class':''}))
    years = forms.ChoiceField(choices=[(x, x) for x in range(1, 5)],widget=forms.Select(attrs={'class':''}))
    moving_avg = forms.ChoiceField(choices=[(x, x) for x in range(5, 101)],widget=forms.Select(attrs={'class':''}))
    stats_include = forms.MultipleChoiceField(choices=STATS_INCLUDE_OPTIONS,widget=forms.CheckboxSelectMultiple)

class NFLForm(forms.Form):

    STATS_INCLUDE_OPTIONS = (
        ('Game - Season Year', 'Season Year'),
        ('Game - Date', 'Date'),
        ('Game - Week', 'Week'),
        ('Game - Game Type', 'Game Type'),
        ('Game - Closing Spread', 'Closing Spread'),
        ('Game - Closing Over-Under', 'Closing Over-Under'),
        ('Game - Moneyline', 'Moneyline'),
        ('Game - Implied Odds', 'Implied Odds'),
        ('Historic - Game - Final Score Spread', 'Final Score Spread in Past Games'),
        ('Historic - Game - Opening Spread', 'Opening Spread in Past Games'),
        ('Historic - Game - Closing Spread', 'Closing Spread in Past Games'),
        ('Historic - Game - Spread Movement', 'Spread Movement in Past Games'),
        ('Historic - Game - Spread Difference', 'Spread Difference in Past Games'),
        ('Historic - Game - Total Score', 'Total Score in Past Games'),
        ('Historic - Game - Opening Over-Under', 'Opening Over-Under in Past Games'),
        ('Historic - Game - Closing Over-Under', 'Closing Over-Under in Past Games'),
        ('Historic - Game - Over-Under Movement', 'Over-Under Movement in Past Games'),
        ('Historic - Game - Over-Under Difference', 'Over-Under Difference in Past Games'),
        ('Historic - Game - Moneyline', 'Moneyline in Past Games'),
        ('Historic - Game - Implied Odds', 'Implied Odds in Past Games'),
        ('Historic - Team and Opponent - 1st Quarter', '1st Quarter Points'),
        ('Historic - Team and Opponent - 2nd Quarter', '2nd Quarter Points'),
        ('Historic - Team and Opponent - 3rd Quarter', '3rd Quarter Points'),
        ('Historic - Team and Opponent - 4th Quarter', '4th Quarter Points'),
        ('Historic - Team and Opponent - Overtime', 'Overtime Points'),
        ('Historic - Team and Opponent - Score', 'Team Score'),
        ('Historic - Team and Opponent - Offense - Rushing - Attempts', 'Offense - Rushing - Attempts'),
        ('Historic - Team and Opponent - Offense - Rushing - Yards', 'Offense - Rushing - Yards'),
        ('Historic - Team and Opponent - Offense - Rushing - Yards Per Attempt', 'Offense - Rushing - Yards Per Attempt'),
        ('Historic - Team and Opponent - Offense - Rushing - Touchdowns', 'Offense - Rushing - Touchdowns'),
        ('Historic - Team and Opponent - Offense - Passing - Completions', 'Offense - Passing - Completions'),
        ('Historic - Team and Opponent - Offense - Passing - Attempts', 'Offense - Passing - Attempts'),
        ('Historic - Team and Opponent - Offense - Passing - Completion Percentage', 'Offense - Passing - Completion Percentage'),
        ('Historic - Team and Opponent - Offense - Passing - Yards', 'Offense - Passing - Yards'),
        ('Historic - Team and Opponent - Offense - Passing - Yards Per Attempt', 'Offense - Passing - Yards Per Attempt'),
        ('Historic - Team and Opponent - Offense - Passing - Touchdowns', 'Offense - Passing - Touchdowns'),
        ('Historic - Team and Opponent - Offense - Passing - Interceptions', 'Offense - Passing - Interceptions'),
        ('Historic - Team and Opponent - Offense - Passing - Interceptions Per Attempt', 'Offense - Passing - Interceptions Per Attempt'),
        ('Historic - Team and Opponent - Offense - Passing - Sacks', 'Offense - Passing - Sacks'),
        ('Historic - Team and Opponent - Offense - Passing - Sack Yards Lost', 'Offense - Passing - Sack Yards Lost'),
        ('Historic - Team and Opponent - Offense - Passing - Net Yards', 'Offense - Passing - Net Yards'),
        ('Historic - Team and Opponent - Offense - Total Yards', 'Offense - Total Yards'),
        ('Historic - Team and Opponent - Offense - Total Touchdowns', 'Offense - Total Touchdowns'),
        ('Historic - Team and Opponent - Offense - Fumbles Recovered', 'Offense - Fumbles Recovered'),
        ('Historic - Team and Opponent - Offense - Fumbles Lost', 'Offense - Fumbles Lost'),
        ('Historic - Team and Opponent - Offense - Turnovers', 'Offense - Turnovers'),
        ('Historic - Team and Opponent - Offense - First Downs', 'Offense - First Downs'),
        ('Historic - Team and Opponent - Offense - Third Downs Made', 'Offense - Third Downs Made'),
        ('Historic - Team and Opponent - Offense - Third Downs Attempted', 'Offense - Third Downs Attempted'),
        ('Historic - Team and Opponent - Offense - Third Down Conversion Percentage', 'Offense - Third Down Conversion Percentage'),
        ('Historic - Team and Opponent - Offense - Fourth Downs Made', 'Offense - Fourth Downs Made'),
        ('Historic - Team and Opponent - Offense - Fourth Downs Attempted', 'Offense - Fourth Downs Attempted'),
        ('Historic - Team and Opponent - Offense - Fourth Down Conversion Percentage', 'Offense - Fourth Down Conversion Percentage'),
        ('Historic - Team and Opponent - Offense - Total Plays', 'Offense - Total Plays'),
        ('Historic - Team and Opponent - Offense - Total Yards Per Play', 'Offense - Total Yards Per Play'),
        ('Historic - Team and Opponent - Offense - Time of Possession', 'Offense - Time of Possession'),
        ('Historic - Team and Opponent - Offense - 2 Point Conversions Made', 'Offense - 2 Point Conversions Made'),
        ('Historic - Team and Opponent - Offense - Extra Points Made', 'Offense - Extra Points Made'),
        ('Historic - Team and Opponent - Defense - Sacks', 'Defense - Sacks'),
        ('Historic - Team and Opponent - Defense - Fumbles Recovered', 'Defense - Fumbles Recovered'),
        ('Historic - Team and Opponent - Defense - Safeties', 'Defense - Safeties'),
        ('Historic - Team and Opponent - Defense - Blocked Kicks and Punts', 'Defense - Blocked Kicks and Punts'),
        ('Historic - Team and Opponent - Defense - Interceptions', 'Defense - Interceptions'),
        ('Historic - Team and Opponent - Offense - Field Goals Made', 'Offense - Field Goals Made'),
        ('Historic - Team and Opponent - Defense - Points Allowed', 'Defense - Points Allowed'),
        ('Historic - Team and Opponent - Penalties', 'Penalties'),
        ('Historic - Team and Opponent - Penalty Yards', 'Penalty Yards'),
        ('Historic - Team and Opponent - Season Games Played', 'Season Games Played'),
        ('Historic - Team and Opponent - Season Wins', 'Season Wins'),
        ('Historic - Team and Opponent - Season Losses', 'Season Losses'),
        ('Historic - Team and Opponent - Season Win Percentage', 'Season Win Percentage'),
    )
    PREDICT_TYPE_OPTIONS = (
        ("Winner", "Winner"),
        ("Winner Against The Spread", "Winner Against The Spread"),
        ("Over-Under Result", "Over-Under"),
    )

    model_name = forms.CharField()
    model_score = forms.FloatField()
    active = forms.BooleanField()
    model_type = forms.CharField()
    predict_type = forms.ChoiceField(choices=PREDICT_TYPE_OPTIONS,widget=forms.Select(attrs={'class':''}))
    years = forms.ChoiceField(choices=[(x, x) for x in range(1, 5)],widget=forms.Select(attrs={'class':''}))
    moving_avg = forms.ChoiceField(choices=[(x, x) for x in range(1, 17)],widget=forms.Select(attrs={'class':''}))
    stats_include = forms.MultipleChoiceField(choices=STATS_INCLUDE_OPTIONS,widget=forms.CheckboxSelectMultiple)

class NFLCBSForm(forms.Form):

    STATS_INCLUDE_OPTIONS = (
        ('Game - Season Year', 'Season Year'),
        ('Game - Date', 'Date'),
        ('Game - Week', 'Week'),
        ('Game - Game Type', 'Game Type'),
        ('Game - Closing Spread', 'Closing Spread'),
        ('Game - Closing Over-Under', 'Closing Over-Under'),
        ('Game - Moneyline', 'Moneyline'),
        ('Game - Implied Odds', 'Implied Odds'),
        ('Historic - Game - Final Score Spread', 'Final Score Spread in Past Games'),
        ('Historic - Game - Opening Spread', 'Opening Spread in Past Games'),
        ('Historic - Game - Closing Spread', 'Closing Spread in Past Games'),
        ('Historic - Game - Spread Movement', 'Spread Movement in Past Games'),
        ('Historic - Game - Spread Difference', 'Spread Difference in Past Games'),
        ('Historic - Game - Total Score', 'Total Score in Past Games'),
        ('Historic - Game - Opening Over-Under', 'Opening Over-Under in Past Games'),
        ('Historic - Game - Closing Over-Under', 'Closing Over-Under in Past Games'),
        ('Historic - Game - Over-Under Movement', 'Over-Under Movement in Past Games'),
        ('Historic - Game - Over-Under Difference', 'Over-Under Difference in Past Games'),
        ('Historic - Game - Moneyline', 'Moneyline in Past Games'),
        ('Historic - Game - Implied Odds', 'Implied Odds in Past Games'),
        ('Historic - Team and Opponent - 1st Quarter', '1st Quarter Points'),
        ('Historic - Team and Opponent - 2nd Quarter', '2nd Quarter Points'),
        ('Historic - Team and Opponent - 3rd Quarter', '3rd Quarter Points'),
        ('Historic - Team and Opponent - 4th Quarter', '4th Quarter Points'),
        ('Historic - Team and Opponent - Overtime', 'Overtime Points'),
        ('Historic - Team and Opponent - Score', 'Team Score'),
        ('Historic - Team and Opponent - Offense - Rushing - Attempts', 'Offense - Rushing - Attempts'),
        ('Historic - Team and Opponent - Offense - Rushing - Yards', 'Offense - Rushing - Yards'),
        ('Historic - Team and Opponent - Offense - Rushing - Yards Per Attempt', 'Offense - Rushing - Yards Per Attempt'),
        ('Historic - Team and Opponent - Offense - Rushing - Touchdowns', 'Offense - Rushing - Touchdowns'),
        ('Historic - Team and Opponent - Offense - Passing - Completions', 'Offense - Passing - Completions'),
        ('Historic - Team and Opponent - Offense - Passing - Attempts', 'Offense - Passing - Attempts'),
        ('Historic - Team and Opponent - Offense - Passing - Completion Percentage', 'Offense - Passing - Completion Percentage'),
        ('Historic - Team and Opponent - Offense - Passing - Yards', 'Offense - Passing - Yards'),
        ('Historic - Team and Opponent - Offense - Passing - Yards Per Attempt', 'Offense - Passing - Yards Per Attempt'),
        ('Historic - Team and Opponent - Offense - Passing - Touchdowns', 'Offense - Passing - Touchdowns'),
        ('Historic - Team and Opponent - Offense - Passing - Interceptions', 'Offense - Passing - Interceptions'),
        ('Historic - Team and Opponent - Offense - Passing - Interceptions Per Attempt', 'Offense - Passing - Interceptions Per Attempt'),
        ('Historic - Team and Opponent - Offense - Passing - Sacks', 'Offense - Passing - Sacks'),
        ('Historic - Team and Opponent - Offense - Passing - Sack Yards Lost', 'Offense - Passing - Sack Yards Lost'),
        ('Historic - Team and Opponent - Offense - Passing - Net Yards', 'Offense - Passing - Net Yards'),
        ('Historic - Team and Opponent - Offense - Total Yards', 'Offense - Total Yards'),
        ('Historic - Team and Opponent - Offense - Total Touchdowns', 'Offense - Total Touchdowns'),
        ('Historic - Team and Opponent - Offense - Fumbles Recovered', 'Offense - Fumbles Recovered'),
        ('Historic - Team and Opponent - Offense - Fumbles Lost', 'Offense - Fumbles Lost'),
        ('Historic - Team and Opponent - Offense - Turnovers', 'Offense - Turnovers'),
        ('Historic - Team and Opponent - Offense - First Downs', 'Offense - First Downs'),
        ('Historic - Team and Opponent - Offense - Third Downs Made', 'Offense - Third Downs Made'),
        ('Historic - Team and Opponent - Offense - Third Downs Attempted', 'Offense - Third Downs Attempted'),
        ('Historic - Team and Opponent - Offense - Third Down Conversion Percentage', 'Offense - Third Down Conversion Percentage'),
        ('Historic - Team and Opponent - Offense - Fourth Downs Made', 'Offense - Fourth Downs Made'),
        ('Historic - Team and Opponent - Offense - Fourth Downs Attempted', 'Offense - Fourth Downs Attempted'),
        ('Historic - Team and Opponent - Offense - Fourth Down Conversion Percentage', 'Offense - Fourth Down Conversion Percentage'),
        ('Historic - Team and Opponent - Offense - Total Plays', 'Offense - Total Plays'),
        ('Historic - Team and Opponent - Offense - Total Yards Per Play', 'Offense - Total Yards Per Play'),
        ('Historic - Team and Opponent - Offense - Time of Possession', 'Offense - Time of Possession'),
        ('Historic - Team and Opponent - Offense - 2 Point Conversions Made', 'Offense - 2 Point Conversions Made'),
        ('Historic - Team and Opponent - Offense - Extra Points Made', 'Offense - Extra Points Made'),
        ('Historic - Team and Opponent - Defense - Sacks', 'Defense - Sacks'),
        ('Historic - Team and Opponent - Defense - Fumbles Recovered', 'Defense - Fumbles Recovered'),
        ('Historic - Team and Opponent - Defense - Safeties', 'Defense - Safeties'),
        ('Historic - Team and Opponent - Defense - Blocked Kicks and Punts', 'Defense - Blocked Kicks and Punts'),
        ('Historic - Team and Opponent - Defense - Interceptions', 'Defense - Interceptions'),
        ('Historic - Team and Opponent - Offense - Field Goals Made', 'Offense - Field Goals Made'),
        ('Historic - Team and Opponent - Defense - Points Allowed', 'Defense - Points Allowed'),
        ('Historic - Team and Opponent - Defense - Fumbles Recovered for a Touchdown', 'Defense - Fumbles Recovered for a TD'),
        ('Historic - Team and Opponent - Defense - Interceptions Returned for a Touchdown', 'Defense - Interceptions Returned for a TD'),
        ('Historic - Team and Opponent - Defense - Blocked Punts and FGs Returned for a TD', 'Defense - Blocked Punts and FGs Returned for a TD'),
        ('Historic - Team and Opponent - Defense - Punts and Kickoffs Returned for a Touchdown', 'Defense - Punts and Kickoffs Returned for a TD'),
        ('Historic - Team and Opponent - Defense - Extra Points Returned for a Touchdown', 'Defense - Extra Points Returned for a TD'),
        ('Historic - Team and Opponent - Defense - 2 Point Conversion Returned for a Touchdown', 'Defense - 2 Point Conversion Returned for a TD'),
        ('Historic - Team and Opponent - Penalties', 'Penalties'),
        ('Historic - Team and Opponent - Penalty Yards', 'Penalty Yards'),
        ('Historic - Team and Opponent - Season Games Played', 'Season Games Played'),
        ('Historic - Team and Opponent - Season Wins', 'Season Wins'),
        ('Historic - Team and Opponent - Season Losses', 'Season Losses'),
        ('Historic - Team and Opponent - Season Win Percentage', 'Season Win Percentage'),
    )
    PREDICT_TYPE_OPTIONS = (
        ("Winner", "Winner"),
        ("Winner Against The Spread", "Winner Against The Spread"),
        ("Over-Under Result", "Over-Under"),
    )

    model_name = forms.CharField()
    model_score = forms.FloatField()
    active = forms.BooleanField()
    model_type = forms.CharField()
    predict_type = forms.ChoiceField(choices=PREDICT_TYPE_OPTIONS,widget=forms.Select(attrs={'class':''}))
    years = forms.ChoiceField(choices=[(x, x) for x in range(1, 5)],widget=forms.Select(attrs={'class':''}))
    moving_avg = forms.ChoiceField(choices=[(x, x) for x in range(1, 17)],widget=forms.Select(attrs={'class':''}))
    stats_include = forms.MultipleChoiceField(choices=STATS_INCLUDE_OPTIONS,widget=forms.CheckboxSelectMultiple)

class NBAForm(forms.Form):

    STATS_INCLUDE_OPTIONS = (
        ('Game - Season Year', 'Season Year'),
        ('Game - Date', 'Date'),
        ('Game - Game Type', 'Game Type'),
        ('Game - Moneyline', 'Moneyline'),
        ('Game - Implied Odds', 'Implied Odds'),
        ('Game - Point Spread', 'Point Spread'),
        ('Game - Over-Under', 'Over-Under'),
        ('Historic - Game - Moneyline', 'Moneyline in Past Games'),
        ('Historic - Game - Implied Odds', 'Implied Odds in Past Games'),
        ('Historic - Game - Point Spread', 'Point Spread in Past Games'),
        ('Historic - Game - Final Score Spread', 'Final Score Spread in Past Games'),
        ('Historic - Game - Spread Difference', 'Spread Difference in Past Games'),
        ('Historic - Game - Over-Under', 'Over-Under in Past Games'),
        ('Historic - Game - Total Score', 'Total Score in Past Games'),
        ('Historic - Game - Over-Under Difference', 'Over-Under Difference in Past Games'),
        ('Historic - Team and Opponent - Score', 'Final Score in Past Games'),
        ('Historic - Team and Opponent - 1st Quarter Points', '1st Quarter Points'),
        ('Historic - Team and Opponent - 2nd Quarter Points', '2nd Quarter Points'),
        ('Historic - Team and Opponent - 3rd Quarter Points', '3rd Quarter Points'),
        ('Historic - Team and Opponent - 4th Quarter Points', '4th Quarter Points'),
        ('Historic - Team and Opponent - Field Goals Made', 'Field Goals Made'),
        ('Historic - Team and Opponent - Field Goal Attempts', 'Field Goal Attempts'),
        ('Historic - Team and Opponent - Field Goal Percentage', 'Field Goal Percentage'),
        ('Historic - Team and Opponent - Two Points Made', 'Two Points Made'),
        ('Historic - Team and Opponent - Two Point Attempts', 'Two Point Attempts'),
        ('Historic - Team and Opponent - Two Point Percentage', 'Two Point Percentage'),
        ('Historic - Team and Opponent - Three Points Made', 'Three Points Made'),
        ('Historic - Team and Opponent - Three Point Attempts', 'Three Point Attempts'),
        ('Historic - Team and Opponent - Three Point Percentage', 'Three Point Percentage'),
        ('Historic - Team and Opponent - Three Point Attempt Rate', 'Three Point Attempt Rate'),
        ('Historic - Team and Opponent - Effective Field Goal Percentage', 'Effective Field Goal Percentage'),
        ('Historic - Team and Opponent - Free Throws Made', 'Free Throws Made'),
        ('Historic - Team and Opponent - Free Throw Attempts', 'Free Throw Attempts'),
        ('Historic - Team and Opponent - Free Throw Percentage', 'Free Throw Percentage'),
        ('Historic - Team and Opponent - Free Throw Attempt Rate', 'Free Throw Attempt Rate'),
        ('Historic - Team and Opponent - Free Throw Factor', 'Free Throw Factor'),
        ('Historic - Team and Opponent - True Shooting Attempts', 'True Shooting Attempts'),
        ('Historic - Team and Opponent - True Shooting Percentage', 'True Shooting Percentage'),
        ('Historic - Team and Opponent - Offensive Rebounds', 'Offensive Rebounds'),
        ('Historic - Team and Opponent - Offensive Rebound Percentage', 'Offensive Rebound Percentage'),
        ('Historic - Team and Opponent - Defensive Rebounds', 'Defensive Rebounds'),
        ('Historic - Team and Opponent - Defensive Rebound Percentage', 'Defensive Rebound Percentage'),
        ('Historic - Team and Opponent - Total Rebounds', 'Total Rebounds'),
        ('Historic - Team and Opponent - Total Rebound Percentage', 'Total Rebound Percentage'),
        ('Historic - Team and Opponent - Assists', 'Assists'),
        ('Historic - Team and Opponent - Assist Percentage', 'Assist Percentage'),
        ('Historic - Team and Opponent - Personal Fouls', 'Personal Fouls'),
        ('Historic - Team and Opponent - Steals', 'Steals'),
        ('Historic - Team and Opponent - Steal Percentage', 'Steal Percentage'),
        ('Historic - Team and Opponent - Player Turnovers', 'Player Turnovers'),
        ('Historic - Team and Opponent - Team Turnovers', 'Team Turnovers'),
        ('Historic - Team and Opponent - Total Turnovers', 'Total Turnovers'),
        ('Historic - Team and Opponent - Turnover Percentage', 'Turnover Percentage'),
        ('Historic - Team and Opponent - Blocks', 'Blocks'),
        ('Historic - Team and Opponent - Block Percentage', 'Block Percentage'),
        ('Historic - Team and Opponent - Possessions', 'Possessions'),
        ('Historic - Team and Opponent - Offensive Rating', 'Offensive Rating'),
        ('Historic - Team and Opponent - Defensive Rating', 'Defensive Rating'),
        ('Historic - Team and Opponent - Pace', 'Pace'),
        ('Historic - Team and Opponent - Season Win Percentage', 'Season Win Percentage'),
    )

    PREDICT_TYPE_OPTIONS = (
        ("Winner", "Winner"),
        ("Winner Against The Spread", "Winner Against The Spread"),
        ("Over-Under Result", "Over-Under"),
    )

    model_name = forms.CharField()
    model_score = forms.FloatField()
    active = forms.BooleanField()
    model_type = forms.CharField()
    predict_type = forms.ChoiceField(choices=PREDICT_TYPE_OPTIONS,widget=forms.Select(attrs={'class':''}))
    years = forms.ChoiceField(choices=[(x, x) for x in range(1, 5)],widget=forms.Select(attrs={'class':''}))
    moving_avg = forms.ChoiceField(choices=[(x, x) for x in range(5, 81)],widget=forms.Select(attrs={'class':''}))
    stats_include = forms.MultipleChoiceField(choices=STATS_INCLUDE_OPTIONS,widget=forms.CheckboxSelectMultiple)

class NHLForm(forms.Form):

    STATS_INCLUDE_OPTIONS = (
        ('Game - Season Year', 'Season Year'),
        ('Game - Date', 'Date'),
        ('Game - Game Type', 'Game Type'),
        ('Game - Closing Implied Odds', 'Closing Implied Odds'),
        ('Game - Closing Spread', 'Closing Spread'),
        ('Game - Closing Spread Moneyline', 'Closing Spread Moneyline'),
        ('Game - Closing Spread Implied Odds', 'Closing Spread Implied Odds'),
        ('Game - Closing Over-Under', 'Closing Over-Under'),
        ('Historic - Game - Opening Moneyline', 'Opening Moneyline in Past Games'),
        ('Historic - Game - Opening Implied Odds', 'Opening Implied Odds in Past Games'),
        ('Historic - Game - Closing Moneyline', 'Closing Moneyline in Past Games'),
        ('Historic - Game - Closing Implied Odds', 'Closing Implied Odds in Past Games'),
        ('Historic - Game - Final Score Spread', 'Final Score Spread in Past Games'),
        ('Historic - Game - Closing Spread', 'Closing Spread in Past Games'),
        ('Historic - Game - Closing Spread Moneyline', 'Closing Spread Moneyline in Past Games'),
        ('Historic - Game - Closing Spread Implied Odds', 'Closing Spread Implied Odds in Past Games'),
        ('Historic - Game - Spread Difference', 'Spread Difference in Past Games'),
        ('Historic - Game - Opening Over-Under', 'Opening Over-Under in Past Games'),
        ('Historic - Game - Closing Over-Under', 'Closing Over-Under in Past Games'),
        ('Historic - Game - Over-Under Movement', 'Over-Under Movement in Past Games'),
        ('Historic - Game - Total Score', 'Total Score in Past Games'),
        ('Historic - Game - Over-Under Difference', 'Over-Under Difference in Past Games'),
        ('Historic - Team and Opponent - Shifts', 'Shifts'),
        ('Historic - Team and Opponent - Shots on Goal', 'Shots on Goal'),
        ('Historic - Team and Opponent - Shots Missed', 'Shots Missed'),
        ('Historic - Team and Opponent - Blocks', 'Blocks'),
        ('Historic - Team and Opponent - Assists', 'Assists'),
        ('Historic - Team and Opponent - Points', 'Points'),
        ('Historic - Team and Opponent - Penalties', 'Penalties'),
        ('Historic - Team and Opponent - Penalty Minutes', 'Penalty Minutes'),
        ('Historic - Team and Opponent - Hits', 'Hits'),
        ('Historic - Team and Opponent - Take Aways', 'Take Aways'),
        ('Historic - Team and Opponent - Give Aways', 'Give Aways'),
        ('Historic - Team and Opponent - Faceoffs Won', 'Faceoffs Won'),
        ('Historic - Team and Opponent - Faceoffs Lost', 'Faceoffs Lost'),
        ('Historic - Team and Opponent - Even Strength - Time on Ice', 'Even Strength - Time on Ice'),
        ('Historic - Team and Opponent - Even Strength - Goals', 'Even Strength - Goals'),
        ('Historic - Team and Opponent - Even Strength - Assists', 'Even Strength - Assists'),
        ('Historic - Team and Opponent - Even Strength - Points', 'Even Strength - Points'),
        ('Historic - Team and Opponent - Power Play - Time on Ice', 'Power Play - Time on Ice'),
        ('Historic - Team and Opponent - Power Play - Goals', 'Power Play - Goals'),
        ('Historic - Team and Opponent - Power Play - Assists', 'Power Play - Assists'),
        ('Historic - Team and Opponent - Power Play - Points', 'Power Play - Points'),
        ('Historic - Team and Opponent - Shorthanded - Time on Ice', 'Shorthanded - Time on Ice'),
        ('Historic - Team and Opponent - Shorthanded - Goals', 'Shorthanded - Goals'),
        ('Historic - Team and Opponent - Shorthanded - Assists', 'Shorthanded - Assists'),
        ('Historic - Team and Opponent - Shorthanded - Points', 'Shorthanded - Points'),
        ('Historic - Team and Opponent - Goaltending - Total Goals Against', 'Goaltending - Total Goals Against'),
        ('Historic - Team and Opponent - Goaltending - Total Shots Against', 'Goaltending - Total Shots Against'),
        ('Historic - Team and Opponent - Goaltending - Total Saves', 'Goaltending - Total Saves'),
        ('Historic - Team and Opponent - Goaltending - Save Percentage', 'Goaltending - Save Percentage'),
        ('Historic - Team and Opponent - Goaltending - Even Strength - Total Saves', 'Goaltending - Even Strength - Total Saves'),
        ('Historic - Team and Opponent - Goaltending - Power Play - Total Saves', 'Goaltending - Power Play - Total Saves'),
        ('Historic - Team and Opponent - Goaltending - Shorthanded - Total Saves', 'Goaltending - Shorthanded - Total Saves'),
        ('Historic - Team and Opponent - Goaltending - Shutout', 'Goaltending - Shutout'),
        ('Historic - Team and Opponent - Season Win Percentage', 'Season Win Percentage')
    )

    PREDICT_TYPE_OPTIONS = (
        ("Winner", "Winner"),
        ("Winner Against The Spread", "Winner Against The Spread"),
        ("Over-Under Result", "Over-Under"),
    )

    model_name = forms.CharField()
    model_score = forms.FloatField()
    active = forms.BooleanField()
    model_type = forms.CharField()
    predict_type = forms.ChoiceField(choices=PREDICT_TYPE_OPTIONS,widget=forms.Select(attrs={'class':''}))
    years = forms.ChoiceField(choices=[(x, x) for x in range(1, 5)],widget=forms.Select(attrs={'class':''}))
    moving_avg = forms.ChoiceField(choices=[(x, x) for x in range(5, 57)],widget=forms.Select(attrs={'class':''}))
    stats_include = forms.MultipleChoiceField(choices=STATS_INCLUDE_OPTIONS,widget=forms.CheckboxSelectMultiple)