# Generated by Django 3.1.1 on 2022-04-01 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20220330_1131'),
        ('notifications', '0005_remove_usernotification_prop_king_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='prop_master_game',
            field=models.ForeignKey(blank=True, help_text='only for prop-master game model use', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_prop_master', to='users.propmaster'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='Notification_type',
            field=models.IntegerField(choices=[(1, 'Like'), (2, 'Comment'), (3, 'UserPostComment'), (4, 'UserPostCommentLike'), (5, 'InviteUserBetaNotification'), (6, 'PropMasterInvite'), (7, 'PropMasterResult')], default=1),
        ),
    ]
