# Generated by Django 4.2.13 on 2024-11-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_thumbs_down_chat_thumbs_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
