# Generated by Django 4.2.13 on 2024-11-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_chat_session_chat_chat_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_pro',
            field=models.BooleanField(default=True),
        ),
    ]
