# Generated by Django 4.2.13 on 2024-12-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chat_is_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
