# Generated by Django 3.1.1 on 2022-02-04 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220204_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='related_sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BlogSports', to='blog.blogsports'),
        ),
    ]
