# Generated by Django 3.1.1 on 2022-08-18 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210826_1120'),
        ('blog', '0003_auto_20220204_0800'),
    ]

    operations = [
    ]
