# Generated by Django 3.1.1 on 2022-08-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_merge_20220818_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sent_email',
            field=models.BooleanField(default=False, help_text='If True means email already sent for this post Author following users'),
        ),
    ]
