# Generated by Django 3.1.1 on 2022-03-02 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220228_1555'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='prop_king_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_prop_king', to='users.propmaster'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='Notification_type',
            field=models.IntegerField(choices=[(1, 'Like'), (2, 'Comment'), (3, 'UserPostComment'), (4, 'UserPostCommentLike'), (5, 'InviteUserBetaNotification'), (6, 'PropKingInvite')], default=1),
        ),
    ]
