# Generated by Django 3.1.1 on 2022-04-07 01:24

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20220401_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='prop_king_game',
            field=models.ForeignKey(blank=True, help_text='only for prop-master game model use', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_prop_master', to='users.propmaster'),
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='prop_king_game',
        ),
    ]
