# Generated by Django 4.2.13 on 2024-07-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_remove_usernotification_prop_king_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
